# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@HEAD
      with:
        # plz work
        base_image: raspios_lite:2023-05-03
        image_additional_mb: 1024
        commands: |
          apt-get install -y golang zlib1g-dev
          cd cmd/neosd
          CGO_ENABLED=1 go build
        copy_artifact_path: cmd/neosd/neosd

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: neosd
        path: neosd
        retention-days: 1
